name: stock_managament_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_lints:
  firebase_core:
  cloud_firestore:
  flutter_iconly:
  flutter_screenutil:
  lottie: ^3.1.0
  get_storage:
  firebase_storage:
  intl: ^0.19.0
  image_picker_web: ^3.1.1
  firebase_pagination: ^3.1.0
  scroll_to_hide: ^2.1.0
  excel: ^2.0.5
  universal_html: ^2.0.3
  file_saver:
  path_provider: ^2.0.2
  fl_chart: ^0.68.0
  path:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/image/

  fonts:
    - family: GilroyBold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: GilroySemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
    - family: GilroyRegular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
  uses-material-design: true
  generate: true
