name: stock_managament_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  flutter: ^3.24.0
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  # CORE & FIREBASE
  cupertino_icons: ^1.0.6         # iOS-style icons for Cupertino widgets
  flutter_lints:                  # Recommended linter rules for Flutter
  firebase_core:                  # Required for all Firebase features
  cloud_firestore:                # Cloud Firestore database integration
  firebase_storage:               # Firebase file storage
  firebase_pagination: ^3.1.0     # Firestore pagination utility
  firebase_storage_web: ^3.9.0           # Firebase Storage for web

  # STATE MANAGEMENT & UTILITIES
  get: ^4.6.6                      # GetX for state management, routing, and DI
  kartal: ^3.5.0                 # Handy extension methods and utilities
  intl: ^0.19.0                   # Internationalization: date, currency, etc.

  # STORAGE & FILE OPERATIONS
  get_storage:                   # Simple key-value local storage (compatible with GetX)
  path_provider: ^2.0.2          # Accessing commonly used locations on filesystem
  path:                          # Path manipulation utilities
  file_saver:                    # Save files to disk (also for web)
  excel: ^2.0.5                  # Read/write Excel files

  # WEB SUPPORT
  image_picker_web: ^3.1.1       # Image picking functionality for Flutter Web
  universal_html: ^2.0.3         # Web-compatible HTML API for Flutter

  # UI COMPONENTS & ANIMATIONS
  flutter_iconly:                # Lightweight icon pack (iOS/Android)
  lottie: ^3.1.0                 # Render animations from Lottie JSON files
  fl_chart: ^0.68.0              # Draw line, bar, pie, and other charts
  scroll_to_hide: ^2.1.0         # Hide widgets on scroll (e.g., bottom navigation)
  flutter_screenutil:            # Adapt UI to different screen sizes (responsive)
  cached_network_image: ^3.0.0
  http_parser:

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  #dart run build_runner watch
  build_runner:
  auto_route_generator:


flutter:
  assets:
    - assets/fonts/
    - assets/lottie/
    - assets/image/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
  uses-material-design: true
  generate: true
